apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patchesStrategicMerge:
- patch.yaml
images:
- name: spazzy757/ephemeral-enforcer
  newName: spazzy757/ephemeral-enforcer
  newTag: pr-14
