apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ephemeral-enforcer
subjects:
- kind: ServiceAccount
  name: ephemeral-enforcer
  namespace: test
roleRef:
  kind: Role
  name: ephemeral-enforcer
  apiGroup: rbac.authorization.k8s.io
